### ISSUE TITLE
"Could not restore theme"

### ISSUE THREAD

**Issue by DealsBeam** [jettheme/core#2]
Thanks for the theme, it is awesome.
However, when I try to apply the theme in blogger / blogspot
I get this message "Could not restore theme"
I've tried to use a different browser, no luck.

**Comment by jettheme** [comment]
Hi DealsBeam
if you can't use restore, you can directly copy and paste the code in the
.xml to edit Html

**Comment by DealsBeam** [comment]
Fixed, thank you!
