### ISSUE TITLE
Blog List and Feed widgets not working on Core template

### ISSUE THREAD

**Issue by gabeweb** [jettheme/core#3]
Hello, first of all I want to thank and congratulate the developer of this Blogger template (really simple, clean theme, no annoying scripts). I stopped using Blogger for a while, apart from how difficult it is to find templates like this that don't sacrifice resources.

Anyway, I downloaded and applied it to my blogs (the file with 2-min version) and the Blog List and Feed widgets don't work correctly, it doesn't load the content of my other linked blogs (that is, it does absolutely nothing, like some script is missing or something).

In my previous template they worked and I had no problem setting up the feeds.

**Comment by jettheme** [comment]
Thank you for using our template.
For your problem, maybe you are right because some blogger widgets are not supported yet, but we will continue to develop templates as the process goes on.
